theme: minima


header_pages:
  - talks_notes.md


title: Seth Nelson | Math PhD Student
author: Seth Nelson
author_profile: false # true: show author profile, false: hide author profile
email: srnelson.math@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my website, where I talk about my math, research, presentations, and notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://srnelson1.github.io" # the base hostname & protocol for your site
github_username:  srnelson1
linkedin_username: seth-nelson-891438229

social:
  name: Seth Nelson
  links:
    - https://github.com/srnelson1
    - https://linkedin.com/in/seth-nelson-891438229
